### ISSUE TITLE
repo已下载，缺演示，可不发文档给我email

### ISSUE THREAD

**Issue by mayinghua** [wangjksjtu/SuperAlarm#20]
进度表做得好！工作内容一目了然。会议记录简洁，但信息全面，可以看出开发在一步步推进。

以上我看到的是项目中给我印象深刻的内容。如有我未能注意，而你认为有特色的内容，可来信提醒我，或者在个人总结中加以说明。

我从github数据上看到，每一个成员图形形状类似，在十月份和11月份均有两个高峰。代码贡献量从大到小：Wangjk，somecat，zhengjilai，Nlisavella，Linboyang，sjrGCKym，和Dulou。全都符合两轮开发阶段特征。表明团队参与度非常高。总体印象：分工清晰，团队凝聚力强。

表扬本组，由于分工明确，所以项目在多个方面都进行了探索：测试、webservice和android！

唯一缺少的是演示部分。我机器刚换，软件都未安装，你们最好直接发给我一个文档，把android和webservice现有的功能描述一下。

**Comment by wangjksjtu** [comment]
马老师，我已经给您发了email，附件里有说明文档。
